name: AdvancedKnockbackFFA
version: '${version}'
main: me.gameisntover.advancedknockbackffa.AdvancedKnockbackFFA
load: STARTUP
description: "The best knockbackffa plugin for minecraft right now!"
authors: [Mmdgio, Marten_mrfcyt]
